"""create page table

Revision ID: dc403f75c97c
Revises: 
Create Date: 2026-01-18 22:16:41.195915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc403f75c97c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index('idx_pages_title', 'pages', ['title'], unique=False)
    op.create_index(op.f('ix_pages_title'), 'pages', ['title'], unique=False)
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_index(op.f('ix_pages_title'), table_name='pages')
    op.drop_index('idx_pages_title', table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
